// gen.mjs — mints ONE shared fixed-point tanh LUT, emitted to JS/Rust/AS identically.
// The ONLY use of float tanh is here, at "compile time", to produce integer constants.
// Runtime in every language uses integer LUT + interpolation → bit-identical across platforms.
import { writeFileSync, mkdirSync } from 'node:fs';

const SCALE = 65536;      // Q16.16
const K = 512;            // segments → K+1 points
const XMIN = -8, XMAX = 8;
const STEP_FIXED = ((XMAX - XMIN) * SCALE) / K; // must be integer
if (!Number.isInteger(STEP_FIXED)) throw new Error('STEP not integer');

const lut = [];
for (let i = 0; i <= K; i++) {
  const x = XMIN + (i * (XMAX - XMIN)) / K;
  lut.push(Math.round(Math.tanh(x) * SCALE)); // integer Q16.16, may be negative
}
// sanity: monotonic non-decreasing (tanh increasing) → interpolation deltas >= 0
for (let i = 1; i < lut.length; i++) if (lut[i] < lut[i-1]) throw new Error('LUT not monotonic at '+i);

mkdirSync('gen', { recursive: true });
writeFileSync('gen/lut.js', `// AUTO-GENERATED by gen.mjs — do not edit\nexport const LUT = [${lut.join(',')}];\n`);
writeFileSync('gen/lut.rs', `// AUTO-GENERATED by gen.mjs — do not edit\npub const LUT: [i64; ${lut.length}] = [${lut.join(',')}];\n`);
writeFileSync('gen/lut.ts', `// AUTO-GENERATED by gen.mjs — do not edit\nexport const LUT: StaticArray<i64> = [${lut.join(',')}];\n`);

console.log(JSON.stringify({
  scale: SCALE, K, xmin: XMIN, xmax: XMAX, step_fixed: STEP_FIXED,
  n: lut.length, center_tanh0: lut[K/2], end_lo: lut[0], end_hi: lut[K]
}));
